<a href="https://colab.research.google.com/github/vedkanojia2304-svg/python_ML-practice/blob/main/Pandas_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Activity 1: Create DataFrame

import pandas as pd

# Create a dictionary
student = {
    "Name": ["A" , "B" , "C" , "D"],
    "Age": [21, 20, 22, 21],
    "Marks": [92, 85, 78, 88]
}

# Create DataFrame
df = pd.DataFrame(student)

# Display DataFrame
print(df)

  Name  Age  Marks
0    A   21     92
1    B   20     85
2    C   22     78
3    D   21     88

In [3]:
# Activity 2: Reading Dataset

from sklearn.datasets import load_iris

# Load the Iris dataset as a Pandas DataFrame
iris = load_iris(as_frame=True)

# Store the DataFrame
df = iris.frame

# Display the first 5 rows
df.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0

In [6]:
#Activity 3: Basic operations

# # Display the last 5 rows
# df.tail()

# # Display the shape (rows, columns)
# df.shape

# # Display the column names
# df.columns

# # Display dataset information
# df.info()

# # Display statistical summary
# df.describe()

# # Display the first 10 rows
# df.head(10)

# # Display a single column
# df["sepal length (cm)"]

# # Display multiple columns
# df[["sepal length (cm)", "petal length (cm)"]]


from IPython.display import display  # for writing each and every output in same cell i am using display()

display(df.tail())
display(df.shape)
display(df.columns)
df.info()
display(df.describe())
display(df.head(10))
display(df["sepal length (cm)"])
display(df[["sepal length (cm)", "petal length (cm)"]])

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
145,6.7,3.0,5.2,2.3,2
146,6.3,2.5,5.0,1.9,2
147,6.5,3.0,5.2,2.0,2
148,6.2,3.4,5.4,2.3,2
149,5.9,3.0,5.1,1.8,2

(150, 5)

Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)', 'target'],
      dtype='object')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
 4   target             150 non-null    int64
dtypes: float64(4), int64(1)
memory usage: 6.0 KB

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
count,150.000000,150.000000,150.000000,150.000000,150.000000
mean,5.843333,3.057333,3.758000,1.199333,1.000000
std,0.828066,0.435866,1.765298,0.762238,0.819232
min,4.300000,2.000000,1.000000,0.100000,0.000000
25%,5.100000,2.800000,1.600000,0.300000,0.000000
50%,5.800000,3.000000,4.350000,1.300000,1.000000
75%,6.400000,3.300000,5.100000,1.800000,2.000000
max,7.900000,4.400000,6.900000,2.500000,2.000000

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0
5,5.4,3.9,1.7,0.4,0
6,4.6,3.4,1.4,0.3,0
7,5.0,3.4,1.5,0.2,0
8,4.4,2.9,1.4,0.2,0
9,4.9,3.1,1.5,0.1,0

0      5.1
1      4.9
2      4.7
3      4.6
4      5.0
      ...
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: sepal length (cm), Length: 150, dtype: float64

     sepal length (cm)  petal length (cm)
0                  5.1                1.4
1                  4.9                1.4
2                  4.7                1.3
3                  4.6                1.5
4                  5.0                1.4
..                 ...                ...
145                6.7                5.2
146                6.3                5.0
147                6.5                5.2
148                6.2                5.4
149                5.9                5.1

[150 rows x 2 columns]

In [8]:
# Activity 4: Selecting Data

# Select only the required columns
df[["sepal length (cm)", "target"]]

# Select the first 5 rows using iloc
df.iloc[:5]

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0

In [9]:
# Select rows from index 10 to 20 using loc
df.loc[10:20]

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
10,5.4,3.7,1.5,0.2,0
11,4.8,3.4,1.6,0.2,0
12,4.8,3.0,1.4,0.1,0
13,4.3,3.0,1.1,0.1,0
14,5.8,4.0,1.2,0.2,0
15,5.7,4.4,1.5,0.4,0
16,5.4,3.9,1.3,0.4,0
17,5.1,3.5,1.4,0.3,0
18,5.7,3.8,1.7,0.3,0
19,5.1,3.8,1.5,0.3,0
20,5.4,3.4,1.7,0.2,0

In [10]:
# Activity 5: Filtering
df[df["target"] == 1]

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
50,7.0,3.2,4.7,1.4,1
51,6.4,3.2,4.5,1.5,1
52,6.9,3.1,4.9,1.5,1
53,5.5,2.3,4.0,1.3,1
54,6.5,2.8,4.6,1.5,1
55,5.7,2.8,4.5,1.3,1
56,6.3,3.3,4.7,1.6,1
57,4.9,2.4,3.3,1.0,1
58,6.6,2.9,4.6,1.3,1
59,5.2,2.7,3.9,1.4,1
60,5.0,2.0,3.5,1.0,1
61,5.9,3.0,4.2,1.5,1
62,6.0,2.2,4.0,1.0,1
63,6.1,2.9,4.7,1.4,1
64,5.6,2.9,3.6,1.3,1
65,6.7,3.1,4.4,1.4,1
66,5.6,3.0,4.5,1.5,1
67,5.8,2.7,4.1,1.0,1
68,6.2,2.2,4.5,1.5,1
69,5.6,2.5,3.9,1.1,1
70,5.9,3.2,4.8,1.8,1
71,6.1,2.8,4.0,1.3,1
72,6.3,2.5,4.9,1.5,1
73,6.1,2.8,4.7,1.2,1
74,6.4,2.9,4.3,1.3,1
75,6.6,3.0,4.4,1.4,1
76,6.8,2.8,4.8,1.4,1
77,6.7,3.0,5.0,1.7,1
78,6.0,2.9,4.5,1.5,1
79,5.7,2.6,3.5,1.0,1
80,5.5,2.4,3.8,1.1,1
81,5.5,2.4,3.7,1.0,1
82,5.8,2.7,3.9,1.2,1
83,6.0,2.7,5.1,1.6,1
84,5.4,3.0,4.5,1.5,1
85,6.0,3.4,4.5,1.6,1
86,6.7,3.1,4.7,1.5,1
87,6.3,2.3,4.4,1.3,1
88,5.6,3.0,4.1,1.3,1
89,5.5,2.5,4.0,1.3,1
90,5.5,2.6,4.4,1.2,1
91,6.1,3.0,4.6,1.4,1
92,5.8,2.6,4.0,1.2,1
93,5.0,2.3,3.3,1.0,1
94,5.6,2.7,4.2,1.3,1
95,5.7,3.0,4.2,1.2,1
96,5.7,2.9,4.2,1.3,1
97,6.2,2.9,4.3,1.3,1
98,5.1,2.5,3.0,1.1,1
99,5.7,2.8,4.1,1.3,1

In [11]:
# Activity 6: Sorting
df.sort_values(by="sepal length (cm)")

"""What it does ?

It sorts the entire DataFrame in ascending order based on the sepal length column.

Smallest sepal length will appear first"""

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
13,4.3,3.0,1.1,0.1,0
8,4.4,2.9,1.4,0.2,0
42,4.4,3.2,1.3,0.2,0
38,4.4,3.0,1.3,0.2,0
41,4.5,2.3,1.3,0.3,0
...,...,...,...,...,...
122,7.7,2.8,6.7,2.0,2
117,7.7,3.8,6.7,2.2,2
118,7.7,2.6,6.9,2.3,2
135,7.7,3.0,6.1,2.3,2
131,7.9,3.8,6.4,2.0,2

In [13]:
df.sort_values(by="sepal length (cm)", ascending=False)

"""This displays the largest sepal length first"""

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
131,7.9,3.8,6.4,2.0,2
122,7.7,2.8,6.7,2.0,2
118,7.7,2.6,6.9,2.3,2
117,7.7,3.8,6.7,2.2,2
135,7.7,3.0,6.1,2.3,2
...,...,...,...,...,...
41,4.5,2.3,1.3,0.3,0
42,4.4,3.2,1.3,0.2,0
8,4.4,2.9,1.4,0.2,0
38,4.4,3.0,1.3,0.2,0
13,4.3,3.0,1.1,0.1,0

In [14]:
""" Assignment
use titanic dataset from kaggle
find the total no. of passengers
find the avg age of surviors and non survivors
list the passenger which are older than 60 years
find the avg fare of each passenger """

# Reading the csv file
import kagglehub
import pandas as pd
import os

# Download latest version
path = kagglehub.dataset_download("yasserh/titanic-dataset")

print("Path to dataset files:", path)

# Show the files inside the folder
print(os.listdir(path))

Using Colab cache for faster access to the 'titanic-dataset' dataset.
Path to dataset files: /kaggle/input/titanic-dataset
['Titanic-Dataset.csv']

In [29]:
# loading the file

df = pd.read_csv(os.path.join(path, "Titanic-Dataset.csv"))

# Display first 5 rows
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [17]:
# find the total no. of passengers

print("Total no. of passengers" , len(df))

Total no. of passengers 891

In [18]:
# Average age of survivors
print("\nAverage age of survivors:")
print(df[df["Survived"] == 1]["Age"].mean())

Average age of survivors:
28.343689655172415

In [22]:
# Average age of non survivors

print("\nAverage age of non survivors:")
print(df[df["Survived"] == 0]["Age"].mean())

Average age of non survivors:
30.62617924528302

In [31]:
# avg fare of each passenger

print(df.groupby("Survived")["Fare"].mean())

# print("\nAverage fare for each passenger class:")
# print(df.groupby("Pclass")["Fare"].mean())

Survived
0    22.117887
1    48.395408
Name: Fare, dtype: float64